[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

# Single redirect rule for React Router SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
